conexao

diff --git a/SSHPLUS/modulos/conexao b/SSHPLUS/modulos/conexao
--- a/SSHPLUS/modulos/conexao
+++ b/SSHPLUS/modulos/conexao
@@ -1,11 +1,13 @@
 #!/bin/bash
 #====================================================
-#	SCRIPT: CONEXAO SSHPLUS MANAGER
-#	DESENVOLVIDO POR:	CRAZY_VPN
-#	DATA ATUALIZACAO:	16-03-2021 
-#	CONTATO TELEGRAM:	http://t.me/crazy_vpn
-#	CANAL TELEGRAM:	http://t.me/sshplus
+#	@Jefssh
 #====================================================
+cor1='\033[41;1;37m'
+cor2='\033[44;1;37m'
+scor='\033[0m'
+GREEN='\033[1;32m'
+YELLOW='\033[1;33m'
+SCOLOR='\033[0m'
 [[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@CRAZY_VPN" ]] && {
 	ram1=$(free -h | grep -i mem | awk {'print $2'})
 	ram2=$(free -h | grep -i mem | awk {'print $4'})
@@ -156,7 +158,6 @@
 				acl url4 dstdomain -i /SSHPLUS?
 				acl payload url_regex -i "$var_pay"
 				acl all src 0.0.0.0/0
-
 				http_access allow url1
 				http_access allow url2
 				http_access allow url3
@@ -460,7 +461,183 @@
 			}
 		fi
 	}
+        fun_v2rayins() {
+			clear
+	        v2rayinst(){
+	            source <(curl -sL https://raw.githubusercontent.com/Jeffssha/NET-WORLD/main/SSHPLUS/modulos/v2ray)
+                    sleep 6
+	        }
+	        if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
+	            echo -e "\E[44;1;37m            INSTALADOR V2RAY             \E[0m"
+	            echo -e "\n${YELLOW}V2RAY JÁ ESTÁ INSTALADO\nDESEJA REINSTALAR? ${SCOLOR}\n"
+	            echo -ne "${GREEN}DESEJA CONTINUAR A REINSTALAÇÃO ? ${YELLOW}[s/n]:${SCOLOR} "
+	            read resp
+	            [[ "$resp" != @(s|sim|S|SIM) ]] && {
+	                echo -e "\n${RED}Retornando...${SCOLOR}"
+	                sleep 2
+	                conexao
+	            }
+	            v2rayinst
+	        else
+	            echo -e "\E[44;1;37m            INSTALADOR V2RAY             \E[0m"
+	            echo -e "\n${YELLOW}ESTEJA CIENTE QUE ESSE METODO É INSTAVEL\nFIQUE CIENTE DOS RISCOS ! ${SCOLOR}\n"
+	            echo -ne "${GREEN}DESEJA CONTINUAR A INSTALACAO ? ${YELLOW}[s/n]:${SCOLOR} "
+	            read resp
+	            [[ "$resp" != @(s|sim|S|SIM) ]] && {
+	                echo -e "\n${RED}Retornando...${SCOLOR}"
+	                sleep 2
+	                conexao
+	            }
+	            v2rayinst
+            fi
+        }
+    	fun_chisel() {
+		clear
+		echo -e "\E[44;1;37m            GERENCIAR CHISEL             \E[0m"
+		echo ""
 
+
+		[[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
+			sks='\033[1;32mON'
+			echo -e "\033[1;33mPORTAS\033[1;37m: \033[1;32m$(netstat -nplt | grep 'docker' | awk {'print $4'} | cut -d: -f2 | xargs)"
+		} || {
+			sks='\033[1;31mOFF'
+		}
+        [[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
+				chiselsts="\033[1;32m◉ "
+			} || {
+				chiselsts="\033[1;31m○ "
+			}
+		echo ""
+		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mATIVAR CHISEL $chiselsts \033[0m"
+		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREINICIAR CHISEL\033[0m"
+		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
+		echo ""
+		echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
+		read resposta
+		if [[ "$resposta" = '1' ]]; then
+			if netstat -nltp | grep 'docker' 1>/dev/null 2>/dev/null; then
+				clear
+				echo -e "\E[41;1;37m             CHISEL              \E[0m"
+				echo ""
+				fun_chiseloff() {
+					docker stop chisel
+                    docker rm chisel
+					docker.io stop chisel
+                    docker.io rm chisel
+
+				}
+				echo -e "\033[1;32mDESATIVANDO CHISEL\033[1;33m"
+				echo ""
+				fun_bar 'fun_chiseloff'
+				echo ""
+				echo -e "\033[1;32mCHISEL DESATIVADO COM SUCESSO!\033[1;33m"
+				sleep 3
+				fun_chisel
+			else
+                clear
+                fun_installdocker() {
+                    _pacotes=("docker" "docker.io")
+                    for _prog in ${_pacotes[@]}; do
+                    apt install $_prog -y
+                    done
+                }
+                echo -e "\n${YELLOW}ESTEJA CIENTE QUE ESSE METODO É INSTAVEL\nPODE OU NÃO FUNCIONAR NA SUA MAQUINA\nFIQUE CIENTE DOS RISCOS ! ${SCOLOR}\n"
+                echo -ne "${GREEN}DESEJA CONTINUAR A INSTALACAO ? ${YELLOW}[s/n]:${SCOLOR} "
+                read resp
+                [[ "$resp" != @(s|sim|S|SIM) ]] && {
+                    echo -e "\n${RED}Retornando...${SCOLOR}"
+                    sleep 2
+                    conexao
+                }
+                echo -e "\n\033[1;32mSuportado Ubuntu 16+\033[1;33m"
+                echo -e "\n\033[1;32mINSTALANDO O CHISEL !\033[1;33m"
+				echo ""
+				fun_bar 'fun_installdocker'
+				clear
+				echo -e "\E[44;1;37m             CHISEL              \E[0m"
+				echo ""
+				echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m: "
+				read porta
+				[[ -z "$porta" ]] && {
+					echo ""
+					echo -e "\033[1;31mPorta invalida!"
+					sleep 3
+					clear
+					fun_chisel
+				}
+				verif_ptrs $porta
+                clear
+                echo -ne "\033[1;32mNome do usuário:\033[1;37m ";read username
+                [[ -z $username ]] && {
+                    echo -e "\n${cor1}Nome de usuário vazio ou invalido!${scor}\n"
+                    fun_chisel
+                }
+                [[ ${username} != ?(+|-)+([a-zA-Z0-9]) ]] && {
+                    echo -e "\n${cor1}Você digitou um nome de usuário inválido!${scor}"
+                    echo -e "${cor1}Não use espaços, acentos ou caracteres especiais!${scor}\n"
+                    fun_chisel
+                }
+                sizemin=$(echo ${#username})
+                [[ $sizemin -lt 2 ]] && {
+                    echo -e "\n${cor1}Você digitou um nome de usuário muito curto${scor}"
+                    echo -e "${cor1}use no mínimo dois caracteres!${scor}\n"
+                    fun_chisel
+                }
+                sizemax=$(echo ${#username})
+                [[ $sizemax -gt 10 ]] && {
+                    echo -e "\n${cor1}Você digitou um nome de usuário muito grande"
+                    echo -e "${cor1}use no máximo 10 caracteres!${scor}\n"
+                    fun_chisel
+                }
+                echo -ne "\033[1;32mSenha:\033[1;37m ";read password
+                [[ -z $password ]] && {
+                    echo -e "\n${cor1}Senha vazia ou invalida!${scor}\n"
+                    fun_chisel 
+                }
+                sizepass=$(echo ${#password})
+                [[ $sizepass -lt 4 ]] && {
+                    echo -e "\n${cor1}Senha curta!, use no mínimo 4 caracteres${scor}\n"
+                    fun_chisel        
+                }
+                echo -e "\n\033[1;32mCONFIGURANDO CHISEL !\033[0m"
+				echo ""
+                fun_inichisel() {
+                    docker run --name chisel -p $porta:$porta -d --restart always jpillora/chisel server -p $porta --socks5 --key supersecret --auth "$username:$password"
+                    docker.io run --name chisel -p $porta:$porta -d --restart always jpillora/chisel server -p $porta --socks5 --key supersecret --auth "$username:$password"
+                }
+                fun_bar 'fun_inichisel'
+                clear
+                echo -e "\n\033[1;32mCHISEL INSTALADO COM SUCESSO !\033[1;31m PORTA: \033[1;33m${porta}\033[0m"
+				sleep 3
+				clear
+				fun_chisel
+            fi
+        elif [[ "$resposta" = '2' ]]; then
+            clear
+            echo -e "\n\033[1;32mREINICIANDO CHISEL !\033[1;33m"
+			echo ""
+            fun_attchisel() {
+                docker restart chisel
+                docker.io restart chisel
+            }
+            fun_attchisel
+            clear
+            echo -e "\n\033[1;32mCHISEL REINICIANDO COM SUCESSO !\033[1;33m"
+            sleep 1
+            fun_chisel
+        elif [[ "$resposta" = '0' ]]; then
+			echo ""
+			echo -e "\033[1;31mRetornando...\033[0m"
+			sleep 1
+			fun_conexao
+		else
+			echo ""
+			echo -e "\033[1;31mOpcao invalida !\033[0m"
+			sleep 1
+			fun_socks
+		fi
+    }
 	inst_ssl() {
 		if netstat -nltp | grep 'stunnel4' 1>/dev/null 2>/dev/null; then
 			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mINDISPONIVEL"
@@ -663,9 +840,9 @@
 			cat /etc/openvpn/ta.key >>~/$1.ovpn
 			echo "</tls-auth>" >>~/$1.ovpn
 		}
-		IP1=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
+		IP1=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'  
 		IP2=$(wget -4qO- "http://whatismyip.akamai.com/")
-		[[ "$IP1" = "" ]] && {
+		[[ "$IP1  
 			IP1=$(hostname -I | cut -d' ' -f1)
 		}
 		[[ "$IP1" != "$IP2" ]] && {
@@ -677,14 +854,14 @@
 			while :; do
 				clear
 
-				opnp=$(cat /etc/openvpn/server.conf | grep "port" | awk {'print $2'})
-				[[ -d /var/www/html/openvpn ]] && {
+				opnp=$(cat /etc/openvpn/server.conf | grep "port" | awk {'
+				[[ 
 					ovpnweb=$(echo -e "\033[1;32m◉ ")
 				} || {
 					ovpnweb=$(echo -e "\033[1;31m○ ")
 				}
 				if grep "duplicate-cn" /etc/openvpn/server.conf >/dev/null; then
-					mult=$(echo -e "\033[1;32m◉ ")
+					mult=$(echo -e "\033[1;32m◉ "
 				else
 					mult=$(echo -e "\033[1;31m○ ")
 				fi
@@ -694,14 +871,14 @@
 				echo ""
 				echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mALTERAR PORTA"
 				echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVER OPENVPN"
-				echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mOVPN VIA LINK $ovpnweb"
+				echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mOVPN VIA LINK $ovpnweb
 				echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mMULTILOGIN OVPN $mult"
 				echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mALTERAR HOST DNS"
 				echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR"
 				echo ""
 				echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m "
 				read option
-				case $option in
+				case $option 
 				1)
 					clear
 					echo -e "\E[44;1;37m         ALTERAR PORTA OPENVPN         \E[0m"
@@ -709,7 +886,7 @@
 					echo -e "\033[1;33mPORTA EM USO: \033[1;32m$opnp"
 					echo ""
 					echo -ne "\033[1;32mQUAL PORTA DESEJA UTILIZAR \033[1;33m?\033[1;37m "
-					read porta
+					read
 					[[ -z "$porta" ]] && {
 						echo ""
 						echo -e "\033[1;31mPorta invalida!"
@@ -1096,7 +1273,7 @@
 			# Adquirindo easy-rsa
 			echo ""
 			fun_dep() {
-				wget -O ~/EasyRSA-3.0.1.tgz "https://github.com/OpenVPN/easy-rsa/releases/download/3.0.1/EasyRSA-3.0.1.tgz"
+				wget -O ~/EasyRSA-3.0.1.tgz "https://github.com/Jeffssha/NET-WORLD/raw/main/SSHPLUS/instalador/EasyRSA-3.0.1.tgz"
 				[[ ! -e $HOME/EasyRSA-3.0.1.tgz ]] && {
 					wget -O ~/EasyRSA-3.0.1.tgz "http://sshplus.xyz/script/EasyRSA-3.0.1.tgz"
 				}
@@ -1849,11 +2026,17 @@ exit 0' >$RCLOCAL
 			clear
 			echo -e "\E[44;1;37m                🌐  MODO DE CONEXAO  🌐              \E[0m\n"
 			echo -e "\033[1;32mSERVICO: \033[1;33mOPENSSH \033[1;32mPORTA: \033[1;37m$(grep 'Port' /etc/ssh/sshd_config | cut -d' ' -f2 | grep -v 'no' | xargs)" && sts6="\033[1;32m◉ "
-			[[ "$(ps x | grep 'slow_dns' | grep -v 'grep'|wc -l)" != '0' ]] && {
+			[[ "$(netstat -tlpn | grep 'docker' | wc -l)" != '0' ]] && {
+				echo -e "\033[1;32mSERVICO: \033[1;33mCHISEL: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'docker' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts8="\033[1;32m◉ "
 			} || {
 				sts8="\033[1;31m○ "
 			}
+			[[ "$(ps x | grep 'slow_dns' | grep -v 'grep'|wc -l)" != '0' ]] && {
+				sts9="\033[1;32m◉ "
+			} || {
+				sts9="\033[1;31m○ "
+			}            
 			[[ "$(netstat -tlpn | grep 'sslh' | wc -l)" != '0' ]] && {
 				echo -e "\033[1;32mSERVICO: \033[1;33mSSLH: \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'sslh' | awk {'print $4'} | cut -d: -f2 | xargs)"
 				sts7="\033[1;32m◉ "
@@ -1892,6 +2075,11 @@ exit 0' >$RCLOCAL
 			} || {
 				sts1="\033[1;31m○ "
 			}
+			xv2ray=`if netstat -tunlp |grep v2ray 1> /dev/null 2> /dev/null; then
+			echo -e "\033[1;32m◉ "
+			else
+			echo -e "\033[1;31m○ "
+			fi`;          
 			echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
 			echo ""
 			echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mOPENSSH $sts6\033[1;31m
@@ -1901,8 +2089,10 @@ exit 0' >$RCLOCAL
 [\033[1;36m05\033[1;31m] \033[1;37m• \033[1;33mPROXY SOCKS $sts4\033[1;31m
 [\033[1;36m06\033[1;31m] \033[1;37m• \033[1;33mSSL TUNNEL $sts3\033[1;31m
 [\033[1;36m07\033[1;31m] \033[1;37m• \033[1;33mSSLH MULTIPLEX $sts7\033[1;31m
-[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mSLOWDNS $sts8\033[1;31m
-[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mVOLTAR \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
+[\033[1;36m08\033[1;31m] \033[1;37m• \033[1;33mCHISEL $sts8\033[1;31m
+[\033[1;36m09\033[1;31m] \033[1;37m• \033[1;33mSLOWDNS $sts9\033[1;31m
+[\033[1;36m10\033[1;31m] \033[1;37m• \033[1;33mV2RAY $xv2ray\033[1;31m
+[\033[1;36m11\033[1;31m] \033[1;37m• \033[1;33mVOLTAR \033[1;32m<\033[1;33m<\033[1;31m< \033[1;31m
 [\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mSAIR \033[1;32m<\033[1;33m<\033[1;31m< \033[0m"
 			echo ""
 			echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
@@ -1935,9 +2125,16 @@ exit 0' >$RCLOCAL
 				fun_sslh
 				;;
 		    8 | 08)
+				fun_chisel
+                ;;              
+		    9 | 09)
 				slow_dns
 				;;
-			9 | 09)
+		    10 | 10)
+				v2raymanager
+				exit;
+				;;                
+			11 | 11)
 				menu
 				;;
 			0 | 00)
